const $=id=>document.getElementById(id);const DEFAULT='https://shib-monitor-api.onrender.com';let prices=[];let ws=null;let reconnectTimer=null;
$('apiUrl').value=localStorage.getItem('shibApiUrl')||DEFAULT;$('save').onclick=()=>{localStorage.setItem('shibApiUrl',$('apiUrl').value.replace(/\/$/,''));connect()};
const fmt=(v,d=6)=>v==null?'--':Number(v).toFixed(d);const qty=v=>v==null?'--':(Number(v)/1e6).toFixed(2)+'M';const pct=v=>v==null?'--':Number(v).toFixed(1)+'%';
function freshness(age){if(age==null)return['UNKNOWN','red','停止'];if(age<=3)return['LIVE','green','使用中'];if(age<=10)return['CAUTION','yellow','注意'];if(age<=30)return['STALE','red','抑制'];return['INVALID','red','停止']}
function render(d){const b=d.book||{},f=d.trade_flow||{},rank=freshness(b.snapshot_age_sec);$('pair').textContent=d.pair||'SHIB/JPY';$('price').textContent=d.price==null?'--':Number(d.price).toFixed(6)+' JPY';$('change').textContent=d.price_change_pct==null?'--':(d.price_change_pct>=0?'+':'')+Number(d.price_change_pct).toFixed(2)+'%';$('change').className=d.price_change_pct>0?'green':d.price_change_pct<0?'red':'';$('ws').textContent=d.ws_connected?'● CONNECTED':'● DISCONNECTED';$('ws').className=d.ws_connected?'green':'red';$('age').textContent=b.snapshot_age_sec==null?'--':Number(b.snapshot_age_sec).toFixed(1)+' 秒';$('fresh').textContent=rank[0];$('fresh').className=rank[1];$('use').textContent=rank[2];$('events').textContent=b.book_change?.events??0;$('bookState').textContent=rank[0]==='LIVE'?'✓ 板情報の状態：正常（LIVE）':`⚠ 板情報の状態：${rank[0]}`;$('bookState').className=rank[1];$('bid').textContent=fmt(b.best_bid);$('ask').textContent=fmt(b.best_ask);$('mid').textContent=fmt(b.mid);$('spread').textContent=b.spread_pct==null?'--':Number(b.spread_pct).toFixed(3)+'%';const mismatch=b.best_bid!=null&&b.best_ask!=null&&d.price!=null&&(d.price<b.best_bid||d.price>b.best_ask);$('match').textContent=mismatch?'⚠ 乖離あり':'✓ 正常';$('match').className=mismatch?'red':'green';
$('imb').textContent=pct(b.imbalance_pct);$('imbLabel').textContent=b.imbalance_pct>=50?'買い優勢':'売り優勢';$('imbLabel').className=b.imbalance_pct>=50?'green':'red';const wt=(b.weighted_bid||0)+(b.weighted_ask||0);$('wimb').textContent=wt?((b.weighted_bid/wt*100).toFixed(1)+'%'): '--';$('wbid').textContent=qty(b.weighted_bid);$('wask').textContent=qty(b.weighted_ask);$('ratio').textContent=b.weighted_ask?(b.weighted_bid/b.weighted_ask).toFixed(2):'--';
const bids=b.bids_top10||[],asks=b.asks_top10||[];$('bookRows').innerHTML=Array.from({length:10},(_,i)=>`<div class="bookrow"><span class="green">${bids[i]?qty(bids[i].amount):'--'}</span><span>${bids[i]?Number(bids[i].price).toFixed(6):'--'}</span><span class="red">${asks[i]?qty(asks[i].amount):'--'}</span></div>`).join('');
$('buy').textContent=pct(f.buy_pct);$('sell').textContent=pct(f.sell_pct);$('buybar').style.width=(f.buy_pct||0)+'%';$('total').textContent=qty((f.buy||0)+(f.sell||0));const usable=d.score_usable===true&&rank[0]!=='INVALID'&&!mismatch;const s=usable?d.score:null;$('score').textContent=s==null?'--':Number(s).toFixed(1);$('scorebar').style.width=(s==null?0:s)+'%';$('label').textContent=s==null?'判定停止':d.label;$('label').className='badge '+(s>=58?'green':s<=42?'red':'yellow');$('components').innerHTML=s==null?'<span class="red">鮮度または価格整合性のため判定停止</span>':Object.entries(d.score_components||{}).map(([k,v])=>`<p>${k}<b>${Number(v).toFixed(1)}</b></p>`).join('');
const notes=[];if(rank[0]==='INVALID')notes.push('✕ 板が30秒以上古いためスコア判定を停止');else if(rank[0]!=='LIVE')notes.push('⚠ 板鮮度：'+rank[0]);if(mismatch)notes.push('⚠ 現在価格とBID/ASKに乖離');if(d.last_error)notes.push('⚠ WS: '+d.last_error);if(!notes.length)notes.push('✓ 板・価格データ正常');$('alerts').innerHTML=notes.map(x=>`<div class="alert">${x}</div>`).join('');$('detail').textContent=`API ${d.version||'--'}\nデータソース ${d.source||'--'}\n板 ${b.ready?'READY':'NOT READY'} / ${b.bid_levels||0} bid / ${b.ask_levels||0} ask\nTOP10 bid ${b.bids_top10?.length||0} / ask ${b.asks_top10?.length||0}\n最終受信 ${b.last_data_received_ts||'--'}\n板更新時刻 ${b.last_update_ts||'--'}\nsequence ${b.sequence??'--'}\nprice ${d.price??'--'}\nWS ${d.ws_connected?'CONNECTED':'DISCONNECTED'}`;prices.push(d.price);if(prices.length>60)prices.shift();$('updated').textContent='最終更新 '+new Date().toLocaleTimeString('ja-JP')}
function connect(){if(ws){try{ws.close()}catch(e){}}const base=($('apiUrl').value||DEFAULT).replace(/^http/,'ws').replace(/\/$/,'');ws=new WebSocket(base+'/ws');ws.onopen=()=>{$('live').textContent='● LIVE';$('live').className='green'};ws.onmessage=e=>{try{render(JSON.parse(e.data))}catch(err){}};ws.onclose=()=>{$('live').textContent='● RECONNECTING';$('live').className='yellow';clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,3000)};ws.onerror=()=>ws.close()}
connect();