const BACKEND_URL="https://shib-monitor-api.onrender.com";
const $=id=>document.getElementById(id);
let prev=null,lastBuy=0,lastSell=0,popupTimer;
function popup(title,text,type){$("popupTitle").textContent=title;$("popupText").textContent=text;const p=$("popup");p.dataset.type=type;p.classList.add("show");clearTimeout(popupTimer);popupTimer=setTimeout(()=>p.classList.remove("show"),7000)}
async function notice(title,text,type){popup(title,text,type);if(!(typeof Notification!=="undefined")||Notification.permission!=="granted")return;try{const r=await navigator.serviceWorker.ready;await r.showNotification(title,{body:text,tag:"shib-"+type,renotify:true})}catch(e){}}
$("notifyBtn").onclick=async()=>{if(!("Notification"in window)){popup("通知非対応","このブラウザは通知API非対応です","sell");return}const p=await Notification.requestPermission();popup(p==="granted"?"通知ON":"通知OFF",p==="granted"?"通知を有効化しました":"通知を許可できませんでした",p==="granted"?"buy":"sell")};
function check(s,d){const th=Math.max(1,+$("threshold").value||10),cd=Math.max(5,+$("cooldown").value||60)*1000,n=Date.now();if(prev!==null){const x=s-prev;if(x>=th&&$("buyEnabled").checked&&n-lastBuy>=cd){lastBuy=n;notice("🟢 SHIB 買い圧力急上昇",`+${x.toFixed(1)}pt / ${s.toFixed(1)}/100（${d.label}）`,"buy")}if(x<=-th&&$("sellEnabled").checked&&n-lastSell>=cd){lastSell=n;notice("🔴 SHIB 売り圧力急上昇",`-${Math.abs(x).toFixed(1)}pt / ${s.toFixed(1)}/100（${d.label}）`,"sell")}}prev=s}
function pct(v){return Number(v||0).toFixed(1)+"%"}
function num(v){return Number(v||0).toLocaleString("ja-JP",{maximumFractionDigits:8})}
function update(d){const b=d.book||{},f=d.trade_flow||{},l=d.large_trade_flow||{},a=d.absorption||{},bc=b.book_change||{},s=+d.score||0,i=+b.imbalance_pct||50,t=+f.buy_pct||50;
$("version").textContent=d.version||"v5.0";$("price").textContent=d.price==null?"--":"¥"+Number(d.price).toLocaleString("ja-JP",{maximumFractionDigits:10});$("score").textContent=s.toFixed(1)+" / 100";$("label").textContent=d.label||"--";$("source").textContent=d.source||"--";
$("bid").textContent=pct(i);$("ask").textContent=pct(100-i);$("bidbar").style.width=i+"%";$("tb").textContent=pct(t);$("ts").textContent=pct(100-t);$("tbar").style.width=t+"%";
$("bookBuy").textContent=pct(bc.buy_pct);$("bookSell").textContent=pct(bc.sell_pct);$("events").textContent=bc.events||0;
$("largeBuy").textContent=pct(l.buy_pct);$("largeSell").textContent=pct(l.sell_pct);$("absBuy").textContent=num(a.buy);$("absSell").textContent=num(a.sell);
$("levels").textContent=`買い ${b.bid_levels||0} / 売り ${b.ask_levels||0} / 合計 ${b.total_levels||0}`;
$("walls").innerHTML=(b.walls||[]).length?b.walls.slice(0,5).map(x=>(x.side==="buy"?"🟢買い壁":"🔴売り壁")+" ¥"+num(x.price)+" / "+num(x.amount)+" SHIB ×"+x.multiple).join("<br>"):"検出なし";
$("detail").textContent=`板Ready: ${b.ready}\nBBO: ${b.best_bid??"--"} / ${b.best_ask??"--"}\nMid: ${b.mid??"--"}\nSpread: ${b.spread_pct??"--"}%\n板数量(選択範囲): buy ${num(b.bid_qty)} / sell ${num(b.ask_qty)}\nWeighted板数量: buy ${num(b.weighted_bid)} / sell ${num(b.weighted_ask)}\n板金額: buy ¥${num(b.bid_notional)} / sell ¥${num(b.ask_notional)}\n使用レベル: buy ${b.bid_levels||0} / sell ${b.ask_levels||0}\n計算窓: ${b.depth_window_pct??"--"}% / 最大${b.max_levels||0} levels\n板インバランス: ${pct(i)} buy\n約定フロー: ${pct(t)} buy\n大口約定: ${pct(l.buy_pct)} buy\n板急変: ${pct(bc.buy_pct)} buy / ${pct(bc.sell_pct)} sell\n吸収候補: buy ${num(a.buy)} / sell ${num(a.sell)}\n巨大注文: ${(b.walls||[]).length}件\nsequence: ${b.sequence??"--"}\n板更新時刻: ${b.last_update_ts??"--"}\n判定: ${d.label||"--"}\nスコア: ${s.toFixed(1)}/100`;check(s,d)}
function connect(){const u=BACKEND_URL.replace(/^http/,"ws").replace(/\/$/,"")+"/ws";const ws=new WebSocket(u);ws.onopen=()=>$("connection").textContent="リアルタイム接続中";ws.onmessage=e=>{try{update(JSON.parse(e.data))}catch(_){}};ws.onclose=()=>{$("connection").textContent="再接続中...";setTimeout(connect,3000)};ws.onerror=()=>ws.close()}connect();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
